import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Snowfall from 'react-snowfall'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center h-100vh bg-gradient-to-b from-[#c2c5be] to-[#E2E2E2]">
        <Snowfall
          color={'#E3E3E3'}
          speed={[0.5, 0.7]}
          snowflakeCount={500}
          radius={[0.5,2.0]}
          wind={[-0.5, 0.5]}
        ></Snowfall> 
      </main>
      <Image className='w-[1690px] barn absolute bottom-0' src="/snowscape.webp" alt="snowy city" width='1690' height="2828" />
    </>
  );
};

export default Home;

