import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Snowfall from 'react-snowfall'

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center h-100vh bg-gradient-to-b from-[#c2c5be] to-[#E2E2E2]">
        <Snowfall
          color={'#E3E3E3'}
          speed={[0.5, 0.7]}
          snowflakeCount={250}
          radius={[2,4]}
          wind={[-0.2, 0.2]}
          style={{
            filter: 'blur(3px)'
          }}
        ></Snowfall> 
        <Snowfall
          color={'#E3E3E3'}
          speed={[1.5, 1.7]}
          snowflakeCount={250}
          radius={[1.5, 3.0]}
          wind={[-0.5, 0.5]}
          style={{
            filter: 'blur(1.0px)'
          }}
        ></Snowfall> 
      </main>
      <div className='overflow-x-hidden w-screen absolute bottom-0'>
        <Image priority={true}  className='overflow-x-hidden w-[1690px] barn' src="/snowscape.webp" alt="snowy city" width='1690' height="2828" />
      </div>
    </>
  );
};

export default Home;

